# Generated by Django 5.2 on 2025-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, default="covers/cover.jpg", null=True, upload_to="covers/"
            ),
        ),
    ]
