# Generated by Django 5.2 on 2025-05-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("special_status", "Can read all books")]},
        ),
    ]
