# Generated by Django 5.2 on 2025-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
